#!/bin/bash 

SCRIPT=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPT")
BASEDIR=$(dirname "$SCRIPTDIR")

SPOOLDIR="$BASEDIR/spool"
PIC="pic.jpg"

LD_LIBRARY_PATH=/usr/local/lib mjpg_streamer -i "input_file.so -f $SPOOLDIR -n $PIC" -o "output_http.so -w /usr/local/www"
